---
include:
  - https://gitlab.exphost.pl/exphost/exphost-helms/-/raw/master/common/gitlab-ci.yml

stages:
  - check
  - upload
  - deploy

upload:
  extends: .upload

deploy-to-dev:
  stage: deploy
  extends: .deploy-to-git-subapp
  environment:
    name: dev
  variables:
    repo: git@gitlab.exphost.pl:exphost/tenant-exphost-services-home-lab.git
    yamlfile: exphost-services.yml
    app: postfix
    #waitapp: tenant-exphost-services-postfix
    #refreshapp: tenant-exphost-services
