apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config-main-cf
data:
  main.cf: |
    compatibility_level = 2
    queue_directory = /var/spool/postfix
    command_directory = /usr/sbin
    daemon_directory = /usr/libexec/postfix
    data_directory = /var/lib/postfix
    mail_owner = postfix
    inet_protocols = all
    mydestination =
    unknown_local_recipient_reject_code = 550
    alias_maps = hash:/etc/aliases
    alias_database = hash:/etc/aliases
    mynetworks_style = host
    
    
    debug_peer_level = 2
    debugger_command =
         PATH=/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin
         ddd $daemon_directory/$process_name $process_id & sleep 5
    sendmail_path = /usr/sbin/sendmail.postfix
    newaliases_path = /usr/bin/newaliases.postfix
    mailq_path = /usr/bin/mailq.postfix
    setgid_group = postdrop
    html_directory = no
    manpage_directory = /usr/share/man
    sample_directory = /usr/share/doc/postfix/samples
    readme_directory = /usr/share/doc/postfix/README_FILES
    smtpd_tls_security_level = may
    smtp_tls_CApath = /etc/pki/tls/certs
    smtp_tls_CAfile = /etc/pki/tls/certs/ca-bundle.crt
    smtp_tls_security_level = may
    meta_directory = /etc/postfix
    shlib_directory = /usr/lib64/postfix
    
    # ============================================
    
    inet_interfaces = all
    
    virtual_mailbox_domains = ldap:/etc/postfix/ldap/virtual_alias_domains
    virtual_alias_maps = ldap:/etc/postfix/ldap/virtual_alias_maps
    virtual_mailbox_base = /var/lib/vmail
    virtual_mailbox_maps = ldap:/etc/postfix/ldap/virtual_mailbox_maps
    virtual_uid_maps = static:230
    virtual_gid_maps = static:230
    
    smtpd_sender_login_maps = ldap:/etc/postfix/ldap/smtpd_sender_login_maps
    
    maillog_file = /dev/stdout
    
