apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-config-main-cf
data:
  main.cf: |
    compatibility_level = 3.6
    queue_directory = /var/spool/postfix
    command_directory = /usr/sbin
    daemon_directory = /usr/libexec/postfix
    data_directory = /var/lib/postfix
    mail_owner = postfix
    unknown_local_recipient_reject_code = 550
    
    debug_peer_level = 2
    debugger_command =
       PATH=/bin:/usr/bin:/usr/local/bin:/usr/X11R6/bin
       ddd $daemon_directory/$process_name $process_id & sleep 5
    sendmail_path = /usr/sbin/sendmail
    newaliases_path = /usr/bin/newaliases
    mailq_path = /usr/bin/mailq
    setgid_group = postdrop
    html_directory = no
    manpage_directory = /usr/share/man
    sample_directory = /etc/postfix
    readme_directory = /usr/share/doc/postfix/readme
    inet_protocols = ipv4
    meta_directory = /etc/postfix
    shlib_directory = /usr/lib/postfix
    # ============================================

    mydestination =
    inet_interfaces = all
    mynetworks_style = host

    virtual_mailbox_domains = ldap:/etc/postfix/ldap/virtual_alias_domains
    virtual_alias_maps = ldap:/etc/postfix/ldap/virtual_alias_maps
    virtual_mailbox_base = /var/lib/vmail
    virtual_mailbox_maps = ldap:/etc/postfix/ldap/virtual_mailbox_maps
    virtual_uid_maps = static:101
    virtual_gid_maps = static:102

    smtpd_sender_login_maps = ldap:/etc/postfix/ldap/smtpd_sender_login_maps

    maillog_file = /dev/stdout
