apiVersion: apps/v1
kind: Deployment
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      containers:
      - name: postfix
        image: {{ .Values.postfix.image }}:{{ .Values.postfix.tag }}
        ports:
        - containerPort: 25
        volumeMounts:
          - mountPath: /etc/postfix/ldap
            name: ldap-config
            readOnly: true
          - name: postfix-config
            mountPath: /etc/postfix/main.cf
            subPath: main.cf
      volumes:
        - name: ldap-config
          secretName: postfix-ldap-config
        - name: postfix-config
          configMap: postfix-config-main-cf
