---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: postfix-config-ldap-alias-domains
spec:
  template: |
    server_host = {{ .Values.ldap.uri }}
    version = 3
    
    bind = yes
    bind_dn = {{ .Values.ldap.bind_dn }}
    bind_pw = {{ "{{" }} bind_pw {{ "}}" }}
    
    search_base = {{ .Values.ldap.search_base }}
    
    query_filter = (|(mailacceptinggeneralid=*@%s)(objectclass=virtual_alias_domains))
    result_attribute = mailacceptinggeneralid
    result_format = %d

  destination_name: postfix-ldap-config
  destination_key: virtual_alias_domains
  destination_type: Secret
  values:
    - name: bane_pw
      source_name: password-password-postfix-from-tenant-exphost-services
      source_type: Secret
      source_key: password
---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: postfix-config-ldap-alias-maps
spec:
  template: |
    server_host = {{ .Values.ldap.uri }}
    version = 3
    
    bind = yes
    bind_dn = {{ .Values.ldap.bind_dn }}
    bind_pw = {{ "{{" }} bind_pw {{ "}}" }}
    
    search_base = {{ .Values.ldap.search_base }}
    scope = sub
    
    query_filter = (|(mailacceptinggeneralid=%s)(objectclass=virtual_alias_maps))
    result_attribute = maildrop

  destination_name: postfix-ldap-config
  destination_key: virtual_alias_maps
  destination_type: Secret
  values:
    - name: bane_pw
      source_name: password-password-postfix-from-tenant-exphost-services
      source_type: Secret
      source_key: password
---
apiVersion: exphost.pl/v1
kind: Template
metadata:
  name: postfix-config-ldap-mailbox-maps
spec:
  template: |
    server_host = {{ .Values.ldap.uri }}
    version = 3
    
    bind = yes
    bind_dn = {{ .Values.ldap.bind_dn }}
    bind_pw = {{ "{{" }} bind_pw {{ "}}" }}
    
    search_base = {{ .Values.ldap.search_base }}
    scope = sub
    
    query_filter = (|(maildrop=%s)(objectclass=virtual_mailbox_maps))
    result_attribute = maildrop
    result_format = %d/%s/mailbox/

  destination_name: postfix-ldap-config
  destination_key: virtual_mailbox_maps
  destination_type: Secret
  values:
    - name: bane_pw
      source_name: password-password-postfix-from-tenant-exphost-services
      source_type: Secret
      source_key: password
