apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  selector:
    matchLabels:
      app: postfix
  podMetricsEndpoints:
  - port: metrics
