apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postfix-vmail
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  storageClassName: longhorn
  volumeMode: Filesystem
