apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postfix-vmail
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
  volumeMode: Filesystem
