---
apiVersion: v1
kind: Service
metadata:
  name: postfix
  labels:
    app: postfix
  annotations:
     metallb.universe.tf/allow-shared-ip: ingress-ip
spec:
  type: LoadBalancer
  ports:
    - name: tcp-smtp
      port: 25
      targetPort: 25
  selector:
    app: postfix
