---
apiVersion: v1
kind: Service
metadata:
  name: postfix
  labels:
    app: postfix
  annotations:
     metallb.universe.tf/allow-shared-ip: ingress-ip
     external-dns.alpha.kubernetes.io/hostname: smtp.{{ .Values.domain }}
spec:
  type: LoadBalancer
  ports:
    - name: tcp-smtp
      port: 25
      targetPort: 25
    - name: tcp-smtps
      port: 465
      targetPort: smtps
    - name: tcp-submission
      port: 587
      targetPort: submission
  selector:
    app: postfix
