apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postfix-ssl-cert
spec:
  secretName: postfix-ssl-cert
  dnsNames:
    - smtp.{{ .Values.domain }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: acme-issuer

