apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postfix
  labels:
    app: postfix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postfix
  serviceName: postfix
  template:
    metadata:
      labels:
        app: postfix
    spec:
      initContainers:
      - name: touch-logfile
        image: {{ .Values.postfix.image }}:{{ .Values.postfix.tag }}
        command:
          - sh
          - -c
          - "touch /var/log/mail/maillog; chown postfix /var/log/mail/maillog; chmod 666 /var/log/mail/maillog"
        volumeMounts:
          - mountPath: /var/log/mail
            name: logs
      containers:
      - name: postfix
        image: {{ .Values.postfix.image }}:{{ .Values.postfix.tag }}
        ports:
        - containerPort: 25
          name: smtp
        - containerPort: 465
          name: smtps
        - containerPort: 587
          name: submission
        volumeMounts:
          - mountPath: /etc/postfix/ldap
            name: ldap-config
            readOnly: true
          - name: postfix-config
            mountPath: /etc/postfix/main.cf
            subPath: main.cf
          - name: postfix-config
            mountPath: /etc/postfix/master.cf
            subPath: master.cf
          - mountPath: /var/lib/vmail
            name: vmail
          - mountPath: /etc/postfix/ssl
            name: ssl
            readOnly: true
          - mountPath: /var/log/mail
            name: logs
          - mountPath: /var/spool/postfix/
            name: postfix-queue
          - mountPath: /var/spool/postfix/public/
            name: sockets
      - name: metrics
        image: registry.gitlab.exphost.pl/torgiren/postfix_exporter:0.3.0
        command:
          - sh
          - -c
          - 'ls -l /var/log/; ls -l  /var/log/mail/; /bin/postfix_exporter --web.listen-address=":9000" --postfix.logfile_path="/var/log/mail/maillog"'
        ports:
        - containerPort: 9000
          name: metrics
        volumeMounts:
          - mountPath: /var/log/mail
            name: logs
          - mountPath: /var/spool/postfix/public/
            name: sockets
      volumes:
        - name: ldap-config
          secret:
            secretName: postfix-ldap-config
        - name: postfix-config
          configMap:
            name: postfix-config-main-cf
        - name: vmail
          persistentVolumeClaim:
            claimName: postfix-vmail
        - name: ssl
          secret:
            secretName: postfix-ssl-cert
        - name: logs
          emptyDir: {}
        - name: sockets
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: postfix-queue
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
